version: "3.9"

services:
  stockexchange:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=stockexchange
    ports:
      - "8080:8080"
    networks:
      - app_network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stockexchange
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s
    networks:
      - app_network

networks:
  app_network: 
volumes:
  mysql_data:
