version: "3.9"

services:
  stockexchange:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
      no_cache: true
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=stockexchange
    ports:
      - "8080:8080"
    volumes:
      - ./tmp/app_logs_vol:/app/logs

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stockexchange
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db_vol:/var/lib/mysql

volumes:
  mysql_data:
