/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `persons`;

CREATE TABLE `persons` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `email` TEXT NOT NULL,
  `password` TEXT NOT NULL)
 ENGINE=InnoDB;

